### ISSUE TITLE
TabNine commands do not work

### ISSUE THREAD

**Issue by Ashirg-ch** [codota/tabnine-intellij#105]
Similar to https://github.com/codota/tabnine-vscode/issues/50, the TabNine commands do not work for me. The autocompletion seems to be impacted as well, with the amount of suggestions being rather low.

I recently started using TabNine on different Win10 systems, but on none of them it worked as it should. I also attempted to fix the problem with the solution provided in the linked Issue, but to no success.

Win10 (several versions, all up to date), IntelliJ 2020.3.0-2 and possibly IntelliJ 2019.3.4, RAM between 8GB and 16GB.

**Comment by yonip23** [comment]
Hi @Ashirg-ch ,
Can you screenshot your `Installation Info` from your Tabnine Hub (example below), as well as the content of your config file (location is provided under `Engine file path`)?

Best regards

![image](https://user-images.githubusercontent.com/67855609/107880359-df21cd80-6ee6-11eb-9c5e-a306adbcbe27.png)

**Comment by Ashirg-ch** [comment]
Hello there,
Here is the requested screenshot and the file content. I assumed that you meant the config file path.
![grafik](https://user-images.githubusercontent.com/51241486/108255329-06c99d80-7154-11eb-8f60-d4df6f8484b2.png)
`{
  "version": "3.3.51",
  "hide_promotional_message": false,
  "beta_enabled": "No",
  "ignore_all_lsp": false,
  "creation_time": "2021-02-05T10:56:58.215975200Z",
  "guuid": "fdf28ff22b2329bd6b1eb491f0194a4c81dd71d71697b5371a39ce12615276c2",
  "semantic_status": {},
  "enable_telemetry": true,
  "user_understands_that_enabling_tabnine_cloud_sends_code_to_tabnine_servers": true,
  "hosted_deep_completions_enabled": "Disabled",
  "tabnine_cloud_host": null,
  "tabnine_cloud_certificate_domain": null,
  "tabnine_cloud_port": null,
  "cloud_whitelist": [],
  "num_of_suggestions": 5,
  "multiline_suggestions": null,
  "api_key": null,
  "api_base_url": null,
  "binary_update_interval_seconds": null,
  "local_enabled": "Unset",
  "disable_local_when_using_battery": false,
  "hide_deep_information_message": false,
  "enable_power_saving_mode": false,
  "rate_limit_interval_seconds": null,
  "rate_limit_amount": null,
  "generation": 40,
  "local_model_size": null,
  "model_hash_override": null,
  "local_indexing": null,
  "heartbeat_interval_seconds": null
}`

**Comment by avnerbarr** [comment]
@Ashirg-ch Are you still having issues or shall I close this ticket?
