### ISSUE TITLE
Auto Imports

### ISSUE THREAD

**Issue by njmaeff** [codota/tabnine-intellij#117]
I am using Webstorm and Typescript.

Tabnine does not work as well as intellij when it comes to calling functions and referencing variables in other modules. Intellij can auto import these symbols when you hit enter. Can you make it so intellij has higher priority in the suggestion list for these symbols. Or perhaps make a hotkey selection possible for the intellij suggested symbols?

![image](https://user-images.githubusercontent.com/31554476/108509894-b1d07900-7272-11eb-8f3b-2a183c573568.png)

**Comment by boaz-codota** [comment]
Hey @njmaeff 

There is a setting you can enable in your IDE to make this work: https://www.jetbrains.com/help/idea/creating-and-optimizing-imports.html#automatically-add-import-statements

Let me know if that did not work. Thanks.

**Comment by njmaeff** [comment]
I have all the auto import settings enabled but I still don't get any imports with the tabnine suggestions. I do if I select one of the intellij suggestions, for example the `writeFileSync` suggestion in the original post. Here is my editor info.

```text
WebStorm 2020.3.2
Build #WS-203.7148.54, built on January 25, 2021
Runtime version: 11.0.9.1+11-b1145.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-64-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 3987M
Cores: 16
Registry: ide.balloon.shadow.size=0, js.debugger.webconsole=false, ide.images.show.chessboard=true
Current Desktop: ubuntu:GNOME
```

**Comment by boaz-codota** [comment]
I suspect that this is a bug in Jetbrains' Auto Imports feature. I'd advise you to submit a bug for them, as we rely on that mechanism (which is working on various other setups we used to try it).

Let me know if I can further assist you.
