### ISSUE TITLE
tabnine free - only for javascript

### ISSUE THREAD

**Issue by boly38** [codota/tabnine-intellij#127]
Hi
First sorry to ask a question here, but I was unable to find an answer

I'm using free version under Intellij CE and I would like to use Tabnine for javascript and I don't want Tabnine completion for my other java-based project.

Is it possible ? how to configure tabnine ?
(I don't see related option into `TabNine::config` local website)
thanks

--- versions
- IntelliJ 2020.3.2 (Community Edition)
- Tabnine 0.3.4

**Comment by boaz-codota** [comment]
Currently, this is not possible. Tabnine works for all files, always.
