### ISSUE TITLE
hope can have better support for typescript 

### ISSUE THREAD

**Issue by bluelovers** [codota/tabnine-intellij#14]
![image](https://user-images.githubusercontent.com/167966/74498608-18aeaa00-4f1c-11ea-94c6-43a155dc62c4.png)

in this case

`_query` is not exists in type `number`

ide: webstorm / idea

**Comment by boaz-codota** [comment]
This is not a typescript thing but an overall limitation of TabNine. We will hopefully crack this in the future as it is in our everyday thoughts and dreams.
