### ISSUE TITLE
Is it possible to limit the use of tabnine to only help with writing code comments? 

### ISSUE THREAD

**Issue by hengzhe-zhang** [codota/tabnine-intellij#140]
Because it is based on natural language processing techniques, I believe this plugin has greatly improved my efficiency when writing code comments. In contrast, I don't think this plug-in is particularly useful when writing codes. As a result,  I hope I can only make this plugin available for writing code comments.

**Comment by yonip23** [comment]
Hi @zhenlingcn 
I am sorry to hear that our plugin isn't useful for your code writing.
Unfortunately, we currently don't support comments only.

Best regards
