### ISSUE TITLE
allow hidden entry when it exists in build-in autocomp

### ISSUE THREAD

**Issue by bluelovers** [codota/tabnine-intellij#15]
![image](https://user-images.githubusercontent.com/167966/74705106-a9072a80-524d-11ea-925c-22813c53c167.png)

first `function` from tabnine
last `function` from ide

hope can have option hidden entry in tabnine list when that exists in build-in list

**Comment by zhoudayang** [comment]
mee too

**Comment by boaz-codota** [comment]
We are aware of this behaviour and it should be fixed in upcoming versions.
