### ISSUE TITLE
Tabnine cannot work properly in Webstorm 2021.1; BinaryCannotRecoverException

### ISSUE THREAD

**Issue by Lutra-Fs** [codota/tabnine-intellij#162]
> Tabnine is not able to function properly. Contact support@tabnine.com
> 
> com.tabnine.binary.exceptions.BinaryCannotRecoverException
> 	at com.tabnine.binary.BinaryProcessRequesterProvider.onDead(BinaryProcessRequesterProvider.java:64)
> 	at com.tabnine.binary.BinaryRequestFacade.executeRequest(BinaryRequestFacade.java:43)
> 	at com.tabnine.binary.BinaryRequestFacade.executeRequest(BinaryRequestFacade.java:23)
> 	at com.tabnine.lifecycle.BinaryStateService.updateState(BinaryStateService.java:32)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
> 	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:223)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
> 	at java.base/java.lang.Thread.run(Thread.java:829)
> 
> Tabnine is not able to function properly. Contact support@tabnine.com
> 
> com.tabnine.binary.exceptions.BinaryCannotRecoverException
> 	at com.tabnine.binary.BinaryProcessRequesterProvider.onDead(BinaryProcessRequesterProvider.java:64)
> 	at com.tabnine.binary.BinaryRequestFacade.executeRequest(BinaryRequestFacade.java:43)
> 	at com.tabnine.binary.BinaryRequestFacade.executeRequest(BinaryRequestFacade.java:23)
> 	at com.tabnine.lifecycle.BinaryNotificationsLifecycle$poll$1.run(BinaryNotificationsLifecycle.kt:26)
> 	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
> 	at java.base/java.util.TimerThread.run(Timer.java:506)
> 

Error on Windows 10 Webstorm 2021.1 Reinstall Tabnine hasn't solved the problem

gz#2103

**Comment by maya-tabnine** [comment]
Can you send Tabnine's logs and your config file?

Your config file should be located at:
{FOLDERID_RoamingAppData}\TabNine (example: C:\Users\Alice\AppData\Roaming\TabNine)

To get Tabnine's log in Webstorm, please open: Help -> Edit Custom Properties...
and insert:
TABNINE_LOG_FILE_PATH = some path to a file
Then restart IDE and wait for the problem to happen.

**Comment by Lutra-Fs** [comment]
intellij log: 
[idea.log](https://github.com/codota/tabnine-intellij/files/6688776/idea.log)
Tabnine Config (Github doesn't support .json upload, so I archived the file):
[tabnine_config.zip](https://github.com/codota/tabnine-intellij/files/6688782/tabnine_config.zip)
I cannot get a Tabnine log with the setting, I use 

> TABNINE_LOG_FILE_PATH = "%appdata%\TabNine\tabnine.log"

for the log, but there is no file generated.

**Comment by Lutra-Fs** [comment]
I am also using Tabnine for VSCode. It works well.

**Comment by Lutra-Fs** [comment]
refers to #99

**Comment by Lutra-Fs** [comment]
I meet this problem after I update Tabnine for Webstorm.

**Comment by Lutra-Fs** [comment]
Hi Maya, I tried the full path, no files generated either.

**Comment by maya-tabnine** [comment]
Try typing 'tabnine::logs' inside the IDE's editor, it should give you the location of the log file.

**Comment by Lutra-Fs** [comment]
Hi Maya, The autocomplete function from Tabnine is not available in my WebStorm.

**Comment by Lutra-Fs** [comment]
I've deleted "%userprofile%/.tabnine", and the error has now disappeared. There is no 3.5.12 in that folder. After the deletion, the 3.5.12 goes to the newest one. But now, my Tabnine cannot give me any suggestion and will create many zombies while running, and I have already added the path to the windows defender exclusions list.

**Comment by Lutra-Fs** [comment]
[wd_log_rCURRENT.txt](https://github.com/codota/tabnine-intellij/files/6722306/wd_log_rCURRENT.txt)
This is the new log file.

**Comment by Lutra-Fs** [comment]
Update: After I fully reinstall Tabnine extension and Webstorm, the extension now back to work

**Comment by Lutra-Fs** [comment]
I will keep this issue open as the issue still exists

**Comment by Lutra-Fs** [comment]
For me, the original issue looks like the extension doesn't pull 3.5.12 binaries from your server, when it tries to call the 3.5.12 binaries it will throw errors. After deleting the binaries, the error has been resolved. But the extension cannot communicate with binaries, it cannot provide any suggestions. From the log, the binaries were called and called again, created more than 10 dead processes. Killing the IDE didn't kill all the processes.

**Comment by Lutra-Fs** [comment]
After getting the newest binaries, instead of reinstalling the extension, I have to reinstall Webstorm to make the connection again.

**Comment by Lutra-Fs** [comment]
@maya-tabnine

**Comment by boaz-codota** [comment]
Wow that is something we need to look further into, but let me just repeat what your conclusions are we are on the same page:

1. Engine binaries tried to update to 3.5.12
2. You had those binaries in the versions folder, and Tabnine tried to run it.
3. They did not work, so Tabnine just kept spinning more and more instances of those, resulting in an overflow of them.
4. You deleted the 3.5.12 folder, Tabnine downloaded a new version (What version? Or was it the same version?)
5. It still didn't work. You uninstalled Webstorm (did you uninstall and reinstall only Tabnine before?), and only then Tabnine started working again (With what engine version?)

Anything else we should know? Something special about your setup?

**Comment by Lutra-Fs** [comment]
nope.
The 3.5.12 has not been downloaded until I clear the folder

**Comment by Lutra-Fs** [comment]
> They did not work, so Tabnine just kept spinning more and more instances of those, resulting in an overflow of them.

That’s the things happens after I clear the folder.

**Comment by Lutra-Fs** [comment]
> It still didn't work. You uninstalled Webstorm (did you uninstall and reinstall only Tabnine before?)

Yes, I tried reinstalling Tabnine only first.

**Comment by boaz-codota** [comment]
So clearing the folder did not help? Or it did?

**Comment by Lutra-Fs** [comment]
> What version? Or was it the same version?

I delete all the things in .tabnine folder, then tabnine get the 3.5.12 ver

**Comment by Lutra-Fs** [comment]
Also I tried to copy the 3.5.12 binary from vscode extension before I clear the folder but it didn't work.

**Comment by boaz-codota** [comment]
Just to be clear, now you have version 3.5.12 and it works?

**Comment by Lutra-Fs** [comment]
Yes

**Comment by Lutra-Fs** [comment]
> So clearing the folder did not help? Or it did?

Clearing folder solve the error listed. But they did not work, so Tabnine just kept spinning more and more instances of those, resulting in an overflow of them.

**Comment by Lutra-Fs** [comment]
> Wow that is something we need to look further into, but let me just repeat what your conclusions are we are on the same page:
> 
> 1. Engine binaries tried to update to 3.5.12
> 2. You had those binaries in the versions folder, and Tabnine tried to run it.
> 3. They did not work, so Tabnine just kept spinning more and more instances of those, resulting in an overflow of them.
> 4. You deleted the 3.5.12 folder, Tabnine downloaded a new version (What version? Or was it the same version?)
> 5. It still didn't work. You uninstalled Webstorm (did you uninstall and reinstall only Tabnine before?), and only then Tabnine started working again (With what engine version?)
> 
> Anything else we should know? Something special about your setup?


 1. Engine binaries tried to update to 3.5.12
 2. You had those binaries (<=3.5.11) in the versions folder, and Tabnine tried to run it.
 3. They did not work, and Tabnine throw BinaryCannotRecoverException
 4. Tried to copy the 3.5.12 binary from the vscode extension folder as the vscode extension  working properly
 5. Delete all the binaries
 6. Tabnine now download 3.5.12 version. Although it solved the exception, it didn't provide any suggestions. Tabnine just kept spinning more and more instances of those, resulting in an overflow of them.
 7.  It still didn't work. You uninstalled Webstorm (did you uninstall and reinstall only Tabnine before?), and only then Tabnine started working again (With what engine version?) 
 8. The problems have now been solved.

**Comment by Lutra-Fs** [comment]
Because the binary is dead, I cannot get any logs.

**Comment by boaz-codota** [comment]
Do you still have the binary that did not work? (In the recycle bin maybe?)

**Comment by Lutra-Fs** [comment]
I am sorry that I am not able to provide that info as I have updated to Windows 11

**Comment by boaz-codota** [comment]
We will look into that, let us know if something like that ever happen again, or if you have any more information.

Thank you for your time!

**Comment by toduyen** [comment]
hi everyone i found the simplest fix. My Tabnine is running fine.
Step 1: uninstall tabnine on WebStorm
Step 2: Delete file .tabnine at C/Users/Username
Step 3: Delete file TabNine at C/Users/Username/AppData/Roaming/TabNine 
Step 4: Open WebStorm install tabnine 


Good luck to you
