### ISSUE TITLE
0.4.4 In Goland 2021.1, the memory is leak

### ISSUE THREAD

**Issue by yk133** [codota/tabnine-intellij#184]
There are many TabNine processes . My computer will crash later,becase no memory to use 
run  one project in Goland 
OS: linux centos 7
Memory :  16G
![6171721](https://user-images.githubusercontent.com/26220461/127436622-a9c4a056-5e52-4f76-86a5-35ee6f80d3bc.png)

gz#4423

**Comment by Eransho** [comment]
Can you share your Tabnine engine version + plugin version?

**Comment by maya-tabnine** [comment]
To find Tabnine's config file that contains those details, please open the Tabnine Hub (click the Tabnine icon in IDE's status bar) and scroll down to "Config file path". 

The file should be located at:
window: {FOLDERID_RoamingAppData}\TabNine. C:\Users\Alice\AppData\Roaming\TabNine
mac : $HOME/Library/Preferences/TabNine /Users/Alice/Library/Preferences/TabNine
linux: $XDG_CONFIG_HOME/TabNine or $HOME/.config/TabNine /home/alice/.config

Thanks!

**Comment by yk133** [comment]
@Eransho  
@maya-tabnine 
this is tabnine_config.json ，plugin version is 0.4.4, look like the engine version is 3.5.31. I have reinstalled it several times.
`
{
  "version": "3.5.31",
  "hide_promotional_message": false,
  "beta_enabled": "No",
  "ignore_all_lsp": false,
  "creation_time": "2021-07-29T11:26:40.344107051Z",
  "guuid": "c1187d73b8*************************************",
  "semantic_status": {},
  "enable_telemetry": true,
  "user_understands_that_enabling_tabnine_cloud_sends_code_to_tabnine_servers": true,
  "hosted_deep_completions_enabled": "Disabled",
  "tabnine_cloud_host": null,
  "tabnine_cloud_certificate_domain": null,
  "tabnine_cloud_port": null,
  "cloud_whitelist": [],
  "num_of_suggestions": 5,
  "multiline_suggestions": null,
  "omit_prefix_suggestions": null,
  "api_key": null,
  "api_base_url": null,
  "binary_update_interval_seconds": null,
  "local_enabled": "Unset",
  "disable_local_when_using_battery": false,
  "hide_deep_information_message": false,
  "enable_power_saving_mode": false,
  "rate_limit_interval_seconds": null,
  "rate_limit_amount": null,
  "generation": 43,
  "local_model_size": null,
  "model_hash_override": null,
  "local_indexing": null,
  "heartbeat_interval_seconds": null,
  "last_service_level": null,
  "override_beams": null,
  "override_context_length": null,
  "onboarding": null,
  "has_git_repos": null,
  "gusr": {
    "dgc": "c1187d73b8*************************************"
  },
  "exclude_file_masks": null
}
`
I hid the guuid，Thanks！

**Comment by dimacodota** [comment]
@yk133 can you please run the binary from the cli with the `--log_to_stderr` flag?
the binary should be located at `$HOME/.tabnine`

**Comment by yk133** [comment]
by the way ， the kernal is  3.10.107-1

@dimacodota  I run and  found panic:
I guess the plugin tried to restart tabNine because of a panic

[2021-08-06T18:07:12.579586422+08:00][ERROR][31719 heartbeat_loop][panic_handling][Some("tabnine/panic_handling/src/lib.rs")][Some(24)] PanicInfo { payload: Any { .. }, message: Some(assertion failed: res.eax == 0), location: Location { file: "/cargo/registry/src/github.com-1ecc6299db9ec823/raw-cpuid-9.0.0/src/lib.rs", line: 271, col: 13 } },    0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>

**Comment by yk133** [comment]
1:  unknown
etc.....

**Comment by dimacodota** [comment]
@yk133 - thanks for the log, can you please complete remove  the `$HOME/.tabnine` folder and restart your IDE?
it should download the latest Tabnine binaries.

**Comment by yk133** [comment]
@dimacodota  It's OK  ! 👌  The new version 3.5.37 solves my problem ! Thank you !!!
