### ISSUE TITLE
Android Studio (when  I building end) uses greater than 70% CPU at all times

### ISSUE THREAD

**Issue by shenyunhuan** [codota/tabnine-intellij#189]
My PC Run Windows 11

gz#4823

**Comment by maya-tabnine** [comment]
Hi, do you have Deep Completions Cloud enabled on Tabnine Hub? 
The cloud eliminates 90% of CPU consumption and 70% memory consumption!
Reach Tabnine Hub by typing "tabnine::config" in the IDE editor and check it out.

**Comment by shenyunhuan** [comment]
> Hi, do you have Deep Completions Cloud enabled on Tabnine Hub?
> The cloud eliminates 90% of CPU consumption and 70% memory consumption!
> Reach Tabnine Hub by typing "tabnine::config" in the IDE editor and check it out.
![image](https://user-images.githubusercontent.com/16234033/128654493-efca381d-e930-4e93-9f24-a4a80dce37a1.png)

**Comment by maya-tabnine** [comment]
Enable the Cloud completions and disable the Local completions.
Try it out, and let me know if it helps!
