### ISSUE TITLE
How to stop auto completing while typing ; or some other kind of symbol in IDEA?

### ISSUE THREAD

**Issue by WesGuo** [codota/tabnine-intellij#19]
IntelliJ IDEA version: 2019.3.3
TabNine version: 0.1.7
Symbol: ;, {, }, (, ), [, ], <, >

**Comment by amircodota** [comment]
I agree regarding `;` not sure about other characters. 
It is useful to get completions after them, at least in some use cases

**Comment by boaz-codota** [comment]
This is not something we plan on changing, but we have improved TabNine's behaviour when new line is expected.
