### ISSUE TITLE
Code suggestion issue

### ISSUE THREAD

**Issue by RidgeA** [codota/tabnine-intellij#2]
I am using the plugin in PHPStorm, where I have a project written on TypeScript.
Enabling TabNine plugin braces code suggestion.

E.g. 
Pressing Ctrl+Space with TabNine disabled:
![Screenshot from 2019-08-23 10-12-02](https://user-images.githubusercontent.com/7588876/63573624-79bd7c80-c58e-11e9-8744-e9ba0c8d26cd.png)

and enabled:
![Screenshot from 2019-08-23 10-10-35](https://user-images.githubusercontent.com/7588876/63573601-690d0680-c58e-11e9-9d9e-080585fca8b8.png)

Ctrl+Space action is Code -> Completion -> Basic 

PHPStorm version 2019.2
TabNine version: 0.1.2

**Comment by willb-the** [comment]
I also get this issue on Ubuntu Linux with Webstorm version 2019.2.3 - TabNine version 0.1.3.

**Comment by cconcise** [comment]
Same issue here with Webstorm 2019.2.3 and TabNine 0.1.3.

**Comment by cconcise** [comment]
After many hours of playing around with the code I may have found a possible solution!

I tracked the root of the issue down to src/main/java/TabNineCompletionContributor.java. If TabNine returns no completion results the plugin decides that no results should be shown period. This means that invoking autocomplete at the start of a line will always yield "No Suggestions."

The code below hands controls back over to Webstorm's autocomplete when TabNine comes back with nothing.

  ```
         TabNineProcess.AutocompleteResponse completions = this.retrieveCompletions(parameters, baseMaxCompletions);
         PrefixMatcher originalMatcher = result.getPrefixMatcher();
         if (completions != null) {
+            if (completions.results.length == 0) {
+                super.fillCompletionVariants(parameters, result);
+                return;
+            }
             result = result.withPrefixMatcher(new TabNinePrefixMatcher(originalMatcher.cloneWithPrefix(completions.old_prefix)));
             result = result.withRelevanceSorter(CompletionSorter.defaultSorter(parameters, originalMatcher).weigh(new TabNineWeigher()));
             result.restartCompletionOnAnyPrefixChange();
```

I'm not a Java developer and this solution was found by hours of trial and error. If anyone can provide guidance on whether this is an acceptable solution that would be appreciated! @zxqfl?

**Comment by willb-the** [comment]
@cconcise this seems like a good fix to me. Maybe submit a PR and @zxqfl can review? Would be nice to get this resolved for the new Webstorm version release today.

**Comment by cconcise** [comment]
While this is definitely still an issue, my fix was not without its own issues. It's looking like no one else is going to fix so I will spend some time learning Java over the ensuing weeks so as to implement a less hacky fix. It's a shame because the version of this plugin for VS Code works friggin awesome whereas the WS version is somewhat of a crapshoot for now.

**Comment by willb-the** [comment]
Yea does look like this version of the plugin gets less attention. However, it was interesting to see that Jetbrains have outlined in their WS 2020 roadmap to implement machine learning based completions

> We’ve started experimenting with code completion powered by machine learning for JavaScript and TypeScript. This will allow WebStorm to deliver more accurate completion suggestions and thus make it easier for you to write quality code faster. 

This from their roadmap blogpost: https://blog.jetbrains.com/webstorm/2019/12/webstorm-2020-1-roadmap/

I wonder if they'll use TabNine under the hood for it or make their own?

**Comment by boaz-codota** [comment]
Hey, we'd love to know whether that buggy behaviour still exists or was it fixed? Thanks!

**Comment by buzzin0609** [comment]
@boaz-codota hey, I just today reinstalled the plugin and it has been fixed :+1: 

thank you
