### ISSUE TITLE
Why does the lib dir exist in the repo?

### ISSUE THREAD

**Issue by solonovamax** [codota/tabnine-intellij#202]
This file does not seem to be used, since you're using the gradle buildsystem: [lib/gson-2.8.5.jar](https://github.com/codota/tabnine-intellij/blob/master/lib/gson-2.8.5.jar)

gz#5469

**Comment by Eransho** [comment]
This is some old leftover, we will remove it.

**Comment by solonovamax** [comment]
Thought so. I'll leave a pr to remove it.
