### ISSUE TITLE
Feedback request: Inline suggestions

### ISSUE THREAD

**Issue by yonip23** [codota/tabnine-intellij#257]
Hi all,
Working with inline suggestions? We'd appreaciate your feedback!

We recently made some improvements and fixes to the inline suggestions, and we want to get even better through iterations.
So if you encounter anything that feels counter-productive regarding the inline suggestion's UI/UX - please comment here or open an issue with link to this discussion, with the following info:

 - OS version: [e.g. Win 10, Mac Catalina]
 - Editor version:
 - Programming language: [e.g. js, ts, c++]
 - Tabnine extension version:
 - Engine version (could be located within Tabnine Hub):
- (If possible) A screenshot / screen recording presenting the issue

To enable inline suggestions, open the hub and go to `Preferences->Completion Preferences->Inline completions (requires restart)` and toggle the checkbox (don't forget to restart).

Thank you all!

gz#10682

**Comment by veeyslaw** [comment]
I would really appreciate a setting to change the button with which to accept these suggestions. I don't like using enter for accepting intellisense completions so I have disabled it to only use tab. But enabling inline completions for tabnine also uses tab for completions, so I can only accept the ones from intellisense with the mouse, which I don't like to use during coding.
