### ISSUE TITLE
Android Studio unable to turn off tabnine suggestions for XML files.

### ISSUE THREAD

**Issue by ernestp** [codota/tabnine-intellij#282]
Tabnine XML suggestion are mostly useless. It does not suggest namespace of parameter, so if I follow suggestions it does not compile. It also make harder to access useful suggestion from Android Studio.

I set in Tabnine to ignore xml extension, however it is still interfere.

gz#11832

**Comment by maya-tabnine** [comment]
Did you set Tabnine not to offer suggestions on your XML file format, and it still suggested? On Tabnine hub?

**Comment by ernestp** [comment]
<img width="931" alt="Screen Shot 2022-02-14 at 20 44 16" src="https://user-images.githubusercontent.com/7553589/153875568-a08a9ee0-e0a0-46af-b4c9-a7615d043583.png">

**Comment by yonip23** [comment]
@ernestp are you a pro user?

**Comment by ernestp** [comment]
@yonip23 No, not yet

**Comment by yonip23** [comment]
@ernestp glad to hear its a "yet" 😁

This feature used to be a pro plan offering, but now it should be available to all users. The fact the its not working for you is a bug on our side - We'll release a fix asap and update here once its done.

Thank you for pointing this out!

**Comment by ernestp** [comment]
Thanks! 

And thanks for great plugin! In some cases it writes few lines of correct code for me (in VS Code for Javascript) and real time saver. I hope in future it can be useful for Android XML layout as well!

**Comment by yonip23** [comment]
Hey @ernestp, letting you know that we released a binary version to beta, containing a fix to this bug - 4.1.3 😁 
If you want to, you can be a beta user and receive this version by toggling `Hub -> Preferences -> Receive beta releases of Tabnine` and restarting your IDE.
Or you can wait a few more days for this version to be released beyond beta :)
Either way, you'll have the fix once the `Hub -> Preferences -> Installation Info -> Engine Version` shows `4.1.3-xx` or higher

Kind regards
