### ISSUE TITLE
Show C# Riders's suggestions, while computing TabNine suggestions

### ISSUE THREAD

**Issue by Toures** [codota/tabnine-intellij#29]
Hi there,

I noticed, that sometimes TabNine takes some extra time to compute suggestions for certain, especially context free (after closing a statement with `;`) or context heavy (lambda operator, for example LINQ statements: `.Select(x => x.SomeProperty)`) situations.

These are situations, where the standard IDE suggestions usually suffice. I also really enjoy TabNines suggestions and coding with an AI partner. :-)

But while the TabNine plugin also delivers standard autocompletion suggestions, it fails to show them on time, while still calculating its own suggestions. Does anyone experience the same on other IDEs/languages?

I would be very happy, if someone knew how to resolve this. Thank you for having a blast coding sofar!

**Comment by boaz-codota** [comment]
This should be fixed, if not please tell us.
