### ISSUE TITLE
[Feature Request] Quick selection of the completion list

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [codota/tabnine-intellij#38]
Is it possible to add different shortcuts to the completion popup list items so that users could quickly select the item they want? For example, when the popup is shown, we could assign `ctrl+1` to the first item, `ctrl+2` to the second, ... `ctrl+0` to the tenth, `ctrl+a` to the eleventh, etc.

For this list:
![image](https://user-images.githubusercontent.com/39968/92414369-835c5700-f186-11ea-8914-db6b4d792f58.png)

`ctrl+5` will choose `= tup`. 

Is will make it faster to choose an item from the list. Right now users have to move their hand to the arrows key or use mouse and select the item they want, which is not very convenient.

**Comment by avichay77** [comment]
Interesting idea, adding it to our list.
