### ISSUE TITLE
Can't start Tabnine

### ISSUE THREAD

**Issue by AndersWinther-Dahl** [codota/tabnine-intellij#422]
Hi,
At my workplace executables isn't allowed to be started from c:\users\...
Is there any way I can make Tabnine install the executables in another folder?

`java.io.IOException: Cannot run program "C:\Users\xxxx\.tabnine\4.4.198\x86_64-pc-windows-gnu\TabNine.exe": CreateProcess error=1260, Programmet er blokeret af en gruppepolitik. Kontakt systemadministratoren for at f.. flere oplysninger
`

`2022-12-07 16:49:24,912 [ 989273]   INFO - #com.tabnine.binary.BinaryProcessRequesterProvider - Can't get completions because Tabnine process is not started yet.`

Best regards,
Anders

gz#19950

**Comment by yonip23** [comment]
Hi @AndersWinther-Dahl 
Thanks for reaching out!
We added this to our backlog, and thanks to you, we'll release a version with this capability to control the binaries' location soon :)
Kind regards

**Comment by AndersWinther-Dahl** [comment]
Seems like you've fixed it:
![image](https://user-images.githubusercontent.com/10073411/216956748-e9525770-973b-4ff6-99e4-66ff2168c28d.png)
Closing this issue :-)
