### ISSUE TITLE
Tabnine 4.4.273 stops working in Windows/PyCharm - spawn of multiple processes/no hub/no autocompletion

### ISSUE THREAD

**Issue by ChameleonRed** [codota/tabnine-intellij#487]
I have problems with Tabnine and I delete as described here:
https://support.tabnine.com/hc/en-us/articles/5409342254481

Version 4.4.273
Plugin 0.8.12

So I:

1. Removed plugin.
2. Delete all files as described.
3. Kill all processes.

It not helps. Delete not works also since debug settings was not deleted so something is not described in article.

Pycharm logs say this (many lines thousands):
`2023-03-17 17:21:27,970 [15424062]   INFO - #com.tabnine.binary.BinaryProcessRequesterProvider - TabNine's response timed out.`

Tabnine logs shows this (it is repeating):
```
DEBUG [hyper::client::pool] [2023-03-17:16:44:29 TabNine-deep-local.exe DEBUG] pooling idle connection for ("https", api.tabnine.com)
DEBUG [reqwest::connect] [2023-03-17:17:04:28 TabNine-deep-local.exe DEBUG] starting new connection: https://api.tabnine.com/
DEBUG [hyper::client::connect::dns] [2023-03-17:17:04:28 TabNine-deep-local.exe DEBUG] resolving host="api.tabnine.com"
DEBUG [hyper::client::connect::http] [2023-03-17:17:04:28 TabNine-deep-local.exe DEBUG] connecting to 34.123.33.186:443
DEBUG [hyper::client::connect::http] [2023-03-17:17:04:28 TabNine-deep-local.exe DEBUG] connected to 34.123.33.186:443
DEBUG [hyper::proto::h1::io] [2023-03-17:17:04:29 TabNine-deep-local.exe DEBUG] flushed 464 bytes
DEBUG [hyper::proto::h1::io] [2023-03-17:17:04:29 TabNine-deep-local.exe DEBUG] parsed 14 headers
DEBUG [hyper::proto::h1::conn] [2023-03-17:17:04:29 TabNine-deep-local.exe DEBUG] incoming body is chunked encoding
DEBUG [hyper::proto::h1::decode] [2023-03-17:17:04:29 TabNine-deep-local.exe DEBUG] incoming chunked header: 0xA (10 bytes)
DEBUG [hyper::proto::h1::decode] [2023-03-17:17:04:29 TabNine-deep-local.exe DEBUG] incoming chunked header: 0x49A (1178 bytes)
DEBUG [hyper::proto::h1::conn] [2023-03-17:17:04:29 TabNine-deep-local.exe DEBUG] incoming body completed
DEBUG [hyper::client::pool] [2023-03-17:17:04:29 TabNine-deep-local.exe DEBUG] pooling idle connection for ("https", api.tabnine.com)
```

process list from windows (too many processes why?):
>tasklist | grep Nine
TabNine.exe                  24180 Console                    1     60□612 K
TabNine-deep-local.exe         380 Console                    1     20□056 K
TabNine-deep-cloud.exe       32516 Console                    1     14□920 K
TabNine-deep-local.exe       34944 Console                    1     15□016 K
TabNine.exe                  33012 Console                    1     31□524 K
TabNine.exe                  37752 Console                    1     31□380 K
TabNine.exe                  37360 Console                    1     31□436 K
TabNine.exe                  39876 Console                    1     31□440 K
TabNine.exe                  25880 Console                    1     31□388 K
TabNine.exe                  27232 Console                    1     31□344 K
TabNine.exe                  33760 Console                    1     31□532 K
TabNine.exe                  27164 Console                    1     31□476 K
TabNine.exe                  33928 Console                    1     31□360 K
TabNine.exe                  42020 Console                    1     31□536 K
TabNine.exe                  54216 Console                    1     31□432 K
TabNine.exe                  41928 Console                    1     31□168 K
TabNine.exe                  94756 Console                    1     34□008 K
WD-TabNine.exe               95176 Console                    1     23□856 K
TabNine.exe                  95220 Console                    1     31□448 K

When I click hub on icon bottom in Pycharm it opens Hub single time and after it create more processes and it not works.

gz#22131<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/22131'>Zendesk ticket #22131</a>)</i>

**Comment by TzufTabnine** [comment]
@ChameleonRed 

Please send us the log files (you can send it to **support@tabnine.com**). Please send us the log files. See [here](https://support.tabnine.com/hc/en-us/articles/5283541356689-Getting-Tabnine-logs-on-JetBrains) how to do that.
