### ISSUE TITLE
Disable Tabnine for some project

### ISSUE THREAD

**Issue by PaulMenheere** [codota/tabnine-intellij#493]
Make it possible to disable Tabnine for certain project

Some customers of mine, (freelancer here) aren't directly open to use their code with AI.
So is it possible to disable the plugin for some project (instead of disabling and restarting phpstorm al together)

gz#22584<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/22584'>Zendesk ticket #22584</a>)</i>

**Comment by TzufTabnine** [comment]
@PaulMenheere 
At the moment you can only disable Tabnine for the IDE or for certain files (for instance .py files)

**Comment by PaulMenheere** [comment]
Is disabling on project base something that we'll see in the future ?
