### ISSUE TITLE
Autocomplete is super confusing in IntelliJ IDEA 2023.1.1

### ISSUE THREAD

**Issue by nazar-pc** [codota/tabnine-intellij#505]
Just tried Tabnine for the very first time and have to disable it, it is super confusing.

The issue is that it shows a suggestion and I can use up/down arrows to select from a few variants, but at the same time IDEA's suggestions are also shown and when I use up/down arrows it cycles through those.

As the result I often pick IDEA's suggestion as more correct, but get Tabnine's suggestion instead that I didn't plan to use.

I have made a small screen recording here: https://youtu.be/pHrtyC54lEo

Once I did see tabnine in that list somehow, but wasn't able to trigger it anymore.

gz#22892<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/22892'>Zendesk ticket #22892</a>)</i>

**Comment by TzufTabnine** [comment]
@nazar-pc 

Are you working with Tab to select the suggestions?

**Comment by nazar-pc** [comment]
IDEA has two actions, which I have configured as follows:
* Enter: "Choose Lookup Item Replace"
* Tab: "Choose Lookup Item"

So I use both in day to day coding, depending on whether I want to replace what follows after the cursor or not.

In the first case Tabnine intercepts action and autocompletes what it wants, in second IDEA autocompletes what it wants. In both cases I see both options, which is not convenient at all.

"Use Hybrid suggestions rendering mode" in Tabnine additional settings seems to get closer to what I want, but likely not completely.

**Comment by TzufTabnine** [comment]
At the moment, the **Tab** is taking the suggestions, and the **Enter** is taking the popup.

**Comment by nazar-pc** [comment]
Well, my expectation was that both would do the same, Tabnine would just be added to the IDEA's autocomplete. Otherwise it is inconsistent with default behavior.

**Comment by TzufTabnine** [comment]
Thanks for the feedback. We will loo into it.
