### ISSUE TITLE
Refine results for strongly typed languages like Rust

### ISSUE THREAD

**Issue by nazar-pc** [codota/tabnine-intellij#507]
I tried using Tabnine with Rust, came to conclusion that it hurts significantly more than it helps.

The goal I had installing this plugin that it'd help picking variables, functions and data structures more accurately than default ML-based autocomplete in IntelliJ IDEA. IDEA by default often doesn't see the obvious: single variable in scope that has matching type and similar name to the field of the data structure where I want to assign something.

Turns out Tabnine is not only helping there, it suggests random function names and variables that do not exist anywhere in the project at all. Even when it autocomples something remotely useful, it requires edits because it adds imaginary stuff that are not relevant instead of adding minimal useful autocomplete.

Rust is a language where A LOT of information is statically available, if only some AI model could use that to do the same basic autocomplete much more accurately...

I was trying "Starter" in "Local Machine" mode (even then it is often faster to type code myself or use IDEA's autocomplete than waiting for Tabnine to hallucinate something that is in most cases not helpful anyway).

gz#22915<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/22915'>Zendesk ticket #22915</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @nazar-pc 

I suggest you try the "Pro" in "Cloud" mode (we have a trial, so the first 14 days will be free of charge) to really experience Tabnine.

**Comment by nazar-pc** [comment]
Unless "Pro" in "Cloud" mode integrates with type information from IDEA, it will not help much. Rust is a very strict language, not analyzing its type system will not be as accurate as what I already get from IDE by default.

Also I'd prefer to not experience delays caused by connecting to the cloud, it is already not as fast as I'd like it to be. And sending everything I type somewhere is not ideal (I know you promise to throw it away, but I learned not to trust something that can't be proved). Configuring self-hosted instance is an option, but I'm not looking forward to heating my room with GPU all the time either.

**Comment by TzufTabnine** [comment]
@nazar-pc 

1. Our cloud model is much better than the local model.
2. Our GPU in the cloud has better performance than your CPU in your machine.
3. Tabnine was written in Rust.
If you want to get all Tabnine can offer, try  "Pro" in "Cloud". Because the setup you are using won't give you all the abilities that Tabnine can offer. Regarding code privacy you can read [here](https://www.tabnine.com/code-privacy)
