### ISSUE TITLE
Tabnine Intellij problem

### ISSUE THREAD

**Issue by joseluisgs** [codota/tabnine-intellij#518]
Hello

Tabnine has disappeared from the Intellij. I activate my pro license and today it disappear from status bar.

I have tried to completely uninstall and reinstall it.

With VSCode I have no problems
I attach the Log

[tabnine-logs_rCURRENT.log](https://github.com/codota/tabnine-intellij/files/11348127/tabnine-logs_rCURRENT.log)
![Screenshot_20230427_230756](https://user-images.githubusercontent.com/47913953/234996275-ed951443-a557-4758-9db6-28b3ba98d76f.png)
![Screenshot_20230427_230821](https://user-images.githubusercontent.com/47913953/234996288-60fd8914-73e6-4cf2-9bff-1adbcc934a3b.png)
![Screenshot_20230427_230923](https://user-images.githubusercontent.com/47913953/234996295-1e6a403a-3228-4a54-bc78-b0a7b2704767.png)

gz#23177<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/23177'>Zendesk ticket #23177</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @joseluisgs 

Can you update your plugin version? You can do it [here](https://plugins.jetbrains.com/plugin/12798-tabnine-ai-code-completion-js-java-python-ts-rust-go-php--more/versions/alpha/310761).
 
Also, do the following:
Shift+Shift (will open a window, see the first picture).
Make sure you click on Tabnine (like in the second picture).
 
Let me know if it works.
 
 
1:
![image](https://user-images.githubusercontent.com/121427912/235339250-38946177-8ef6-44bb-b031-962f8eaba04a.png)


 
2:
![image](https://user-images.githubusercontent.com/121427912/235339253-1a57677c-9093-4a6a-aee9-c8f28085d441.png)

**Comment by joseluisgs** [comment]
Hi, 
Thank you so much! solved! I need this update! :)

**Comment by TzufTabnine** [comment]
Glad to hear that.
Enjoy Tabnine!

**Comment by joseluisgs** [comment]
Hi

Today I have the same problem, Tabnine widget disappear from StatusBar widget again

**Comment by TzufTabnine** [comment]
Hi @joseluisgs 
Can you send us the Help -> About in your IDE?
It should look similar to that:

![image](https://user-images.githubusercontent.com/121427912/236664263-1cf7a739-f195-494e-b42b-bd8bc89c8baf.png)

**Comment by joseluisgs** [comment]
Hi
there is my version
![Screenshot_20230508_124555](https://user-images.githubusercontent.com/47913953/236804938-f13a33ba-4167-4bf5-8841-0df7e441dc3a.png)
![Screenshot_20230508_124635](https://user-images.githubusercontent.com/47913953/236804947-f6c5eff2-b37e-4fa1-9b5b-42d6d40030e5.png)

**Comment by TzufTabnine** [comment]
@joseluisgs 
Thanks, we are working on a resolution.
