### ISSUE TITLE
Tabnine still exists on your Mac after you uninstall it

### ISSUE THREAD

**Issue by szh-1997** [codota/tabnine-intellij#541]
I accidentally uninstalled Tabnine once today, and accidentally found that Tabnine is still running in my local after uninstallation and occupies CPU. Why is this?
![CleanShot2023-06-19 08 22 06](https://github.com/codota/tabnine-intellij/assets/82578219/c1c01e6e-23a2-419a-a2a5-66581cd4d80a)

gz#24327<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/24327'>Zendesk ticket #24327</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @szh-1997 
You can fully delete Tabnine from your computer. You need to delete all the folders associated with Tabnine. When you work on Local Model Mode, Tabnine is using your CPU.
