### ISSUE TITLE
Show shorter completions

### ISSUE THREAD

**Issue by turiondolby** [codota/tabnine-intellij#563]
Hi there. For a while now, the completions Tabnine provides are much longer and forces me to type more 😆 

In the image below, it would be great if "saveHandler" was an option, in addition to those suggested:
![image](https://github.com/codota/tabnine-intellij/assets/8764796/7519ca68-cb12-49ee-bb13-da8a12038805)

Is it possible to show shorter completions and also show the longer completions so I can just type a few letters then Tab, and a few letters and Tab etc?

Thank you.

gz#24805<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/24805'>Zendesk ticket #24805</a>)</i>

**Comment by yonip23** [comment]
Hi @turiondolby 
Have you tried our inline completions? it's a more suitable UX for these longer completions.
I presume you have "Use Hybrid suggestions rendering mode" enabled in the hub, so open the Hub -> Settings -> Advanced Settings, and toggle off this option
![image](https://github.com/codota/tabnine-intellij/assets/67855609/6256417b-0c34-408c-aa59-339d6b4db6d7)
