### ISSUE TITLE
启用之后，在引号中输入中文问题

### ISSUE THREAD

**Issue by turing1989** [codota/tabnine-intellij#593]
启用之后，在引号中输入中文问题，输入多余1个的中文，最终只显示1个中文

gz#25364<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/25364'>Zendesk ticket #25364</a>)</i>

**Comment by amirbilu** [comment]
Hi turing1989,

Thanks for using Tabnine!

I'm not sure I fully understand your request,
It would be great if you could provide some more info.

Thank you,

Robbie Flores
Tabnine Support
<br><p><em><small>°°°</small></em></p>

**Comment by turing1989** [comment]
I upgraded the version and this issue has been solved, thanks

**Comment by amirbilu** [comment]
Hi turing1989,

Awesome! Glad to hear that it is working.
Just remember, we’re always an email away if you need help.

BTW, can I ask you for a favor? How about sharing a positive review on the marketplace?
Whether you use **VSCode**** **/ **JetBrains**** **/ **Eclipse**, we would appreciate it.

All the best,

Tzuf Stokelman
Tabnine Support
<br><p><em><small>°°°</small></em></p>
