### ISSUE TITLE
Webstorms breaks copy/paste

### ISSUE THREAD

**Issue by aejuice-github** [codota/tabnine-intellij#599]
Every 3 minutes it breaks copy/paste and there is a red flashing alert that cannot be turned off in IDE. 

Latest webstorm version. Became UNUSEBLE!

gz#25450<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/25450'>Zendesk ticket #25450</a>)</i>

**Comment by zaycker** [comment]
same with IDEA

**Comment by zaycker** [comment]
#597

**Comment by zaycker** [comment]
https://github.com/codota/tabnine-intellij/issues/553#issuecomment-1652332913

**Comment by pro-verstka** [comment]
Same problem, temporary disabled the plugin

**Comment by TzufTabnine** [comment]
Hi all,
Make sure you have the latest version of Tabnine (1.0.37). It should solve the issue. Please let us know if it is working. Sorry for the bad experience.

**Comment by TzufTabnine** [comment]
@roorooroofus 
Can you send us the logs (engine+idea)? See [here](https://support.tabnine.com/hc/en-us/articles/5283541356689-Getting-Tabnine-logs-on-JetBrains) how to do that.
You can send it here or to support@tabnine.com

**Comment by TzufTabnine** [comment]
@roorooroofus ,
We deployed a fix (version 1.0.38). Please update the new version and let us know if it works now.
