### ISSUE TITLE
ctrl+Z写了半天的代码全部丢失

### ISSUE THREAD

**Issue by angel-yi** [codota/tabnine-intellij#600]
写了半天的代码，撤回操作全部丢失了，测试关闭了这个插件，没有这个问题出现，严重bug！！！

gz#25463<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/25463'>Zendesk ticket #25463</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @angel-yi 
Make sure you have the latest version of Tabnine. It should solve the issue.
Check [here](https://support.tabnine.com/hc/en-us/articles/5460798381201-Plugin-version).

**Comment by TzufTabnine** [comment]
https://github.com/codota/tabnine-intellij/issues/601
