### ISSUE TITLE
Distracting logo in autocompletion (and status bar)

### ISSUE THREAD

**Issue by InvisibleSmiley** [codota/tabnine-intellij#64]
First of all thanks for the plugin! I really enjoy using it!

I don't know whether this is from a recent TabNine update or switch to PhpStorm 2020.3 EAP 5, but now I have a rather distracting icon in front of the TabNine autocomplete suggestions (and in the status bar as well).

I understand this is your logo and you're probably proud of it, but I ask you to consider either making it less distracting in front of the autocomplete suggestions (smaller, lighter, ...) or add the option to remove the icon there (as it used to be).

In general this also applies to the status bar, but there I already have the option to remove/hide it as a workaround.

TabNine 0.2.4
PhpStorm 2020.3 EAP Build #PS-203.5419.32
Windows 10

**Comment by boaz-codota** [comment]
Thanks for reaching out to us!

We did not think our logo would be of such inconvenience to you and to other users, but we do understand that it is. We are thinking on a solution right know and will be publishing new versions of TabNine to address that.

Thanks again, and please keep on providing us valuable feedback to enable us to improve TabNine a bit more everyday.

**Comment by boaz-codota** [comment]
Replaced the logo
