### ISSUE TITLE
I've downloaded the source code and directly executed `./gradlew buildPlugin` to package the plugin. However, after completing the installation, there is no response or indication that the plugin is working. What could be the reason for this issue, and how should I go about resolving it?

### ISSUE THREAD

**Issue by wwwworkhard** [codota/tabnine-intellij#708]
I've downloaded the source code and directly executed `./gradlew buildPlugin` to package the plugin. However, after completing the installation, there is no response or indication that the plugin is working. What could be the reason for this issue, and how should I go about resolving it?

gz#28644<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/28644'>Zendesk ticket #28644</a>)</i>

**Comment by TzufTabnine** [comment]
The issue is not clear. Please elaborate and send us some screenshot/video if you can
