### ISSUE TITLE
Error running vdb Qdrant process

### ISSUE THREAD

**Issue by nolik** [codota/tabnine-intellij#709]
Hi, completed fresh install of system:
`Linux 6.7.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 05 Feb 2024 22:07:49 +0000 x86_64 GNU/Linux`
and IDEA:
```
IntelliJ IDEA 2023.3.3 (Ultimate Edition)
Build #IU-233.14015.106, built on January 25, 2024
Licensed to Godel Technologies / Ihar Novik
Subscription is active until November 15, 2024.
Runtime version: 17.0.9+7-b1087.11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.7.4-arch1-1
GC: G1 Young Generation, G1 Old Generation
Memory: 3860M
Cores: 16
Registry:
  debugger.watches.in.variables=false
  debugger.new.tool.window.layout=true
  documentation.show.toolbar=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  IdeaVIM (2.8.4)
  name.kropp.intellij.makefile (233.13135.65)
  Key Promoter X (2023.3.0)
  com.tabnine.TabNine (1.54.0)
  google-java-format (1.19.2.0)
  com.intellij.mermaid (0.0.19+IJ.232)
  Pythonid (233.14015.106)
  izhangzhihao.rainbow.brackets (2024.2.1)
  com.intellij.bigdatatools.core (233.14015.106)
  org.sonarlint.idea (10.3.0.77475)
Kotlin: 233.14015.106-IJ
Current Desktop: Undefined
```

Trying to run in Idea latest version of Tabline - 1.54.0
and getting in logs:
`ERROR [similarity_search::vdb_server_starter] [2024-02-13:09:57:44 TabNine ERROR] Error running vdb Qdrant process did not connect within PT60S`

I know that it's smth related to qdrant vector db. But don't have idea why process can't start.

gz#29684<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/29684'>Zendesk ticket #29684</a>)</i>

**Comment by TzufTabnine** [comment]
@nolik Please send the logs in this directory:
~/.local/share/TabNine/servers/vdb/1.7.3-fix.1/logs

**Comment by nolik** [comment]
> @nolik Please send the logs in this directory: ~/.local/share/TabNine/servers/vdb/1.7.3-fix.1/logs
in common logs:
`INFO [cloud2_utils::snippet_suggestions_host] [2024-02-13:14:01:52 TabNine INFO] enrichment config - returning default config
ERROR [similarity_search::vdb_server_starter] [2024-02-13:14:01:53 TabNine ERROR] Error running vdb Qdrant process did not connect within PT60S
INFO [cloud2_utils::snippet_suggestions_host] [2024-02-13:14:02:22 TabNine INFO] enrichment config - returning default config
INFO [cloud2_utils::snippet_suggestions_host] [2024-02-13:14:02:52 TabNine INFO] enrichment config - returning default config
ERROR [similarity_search::vdb_server_starter] [2024-02-13:14:02:53 TabNine ERROR] Error running vdb Qdrant process did not connect within PT60S`

strange there is logs from vdb when I observe current failure:
`[2024-02-13 14:00:52.111326 +01:00] INFO [vectordb/server_runner/src/main.rs:82] Tabnine-server-runner starting for vdb
[2024-02-13 14:00:52.312170 +01:00] INFO [vectordb/server_runner/src/main.rs:88] Server vdb is already running
[2024-02-13 14:01:53.286769 +01:00] INFO [vectordb/server_runner/src/main.rs:82] Tabnine-server-runner starting for vdb
[2024-02-13 14:01:53.487200 +01:00] INFO [vectordb/server_runner/src/main.rs:88] Server vdb is already running
[2024-02-13 14:02:53.425345 +01:00] INFO [vectordb/server_runner/src/main.rs:82] Tabnine-server-runner starting for vdb
[2024-02-13 14:02:53.625815 +01:00] INFO [vectordb/server_runner/src/main.rs:88] Server vdb is already running`

**Comment by TzufTabnine** [comment]
@nolik Please send the full logs

**Comment by nolik** [comment]
@TzufTabnine 
common log (after plugin reinstallation): 
[tabline_rCURRENT.log](https://github.com/codota/tabnine-intellij/files/14269133/tabline_rCURRENT.log)

vectorDb logs at the same time:
[vdb_rCURRENT.log](https://github.com/codota/tabnine-intellij/files/14269142/vdb_rCURRENT.log)

**Comment by amircodota** [comment]
Hi @nolik

From the logs it looks like vdb successfully starts and listens on port 6335, but tabnine fails to connect to it.
Could there be some security software on your machine that is blocking it?

If not, can you close your IDE and make sure no Tabnine and no vdb processes are running on your machine.

Then run the following command

```
$HOME/.local/share/TabNine/servers/vdb/1.7.3-fix.1/download/vdb --config-path $HOME/.local/share/TabNine/servers/vdb/1.7.3-fix.1/download/config.yaml
```

Make sure the process remains running and that no errors are reported.

Then try to connect to vdb via telnet or some other software that can check for a tcp connection

```
telnet localhost 6335
```

Let us know the outcome

**Comment by nolik** [comment]
He @amircodota . Thx for help. Seems after update to the latest version of IntelliJ IDEA 2023.3.4 issue been resolved themself.
