### ISSUE TITLE
Tabnine Chat JCEF Error with Android Studio 

### ISSUE THREAD

**Issue by KemalEnigma** [codota/tabnine-intellij#710]
I've tried various options so far changing Java Runtime  for any other than defaults and did not succeed  I'm using Tabnine Pro with Android studio for Flutter
![Screenshot 2024-03-21 at 10 32 13](https://github.com/codota/tabnine-intellij/assets/162964106/a7c658e5-81fe-4ec8-a8d8-00021a917c99)

gz#30461<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/30461'>Zendesk ticket #30461</a>)</i>

**Comment by TzufTabnine** [comment]
What is your IDE version? @KemalEnigma

**Comment by TzufTabnine** [comment]
Can you please:
Select Help > Find Action from the Android Studio menu.
Look for Registry...
Find the ide.browser.jcef.sandbox.enable option in the list and disable it
Restart
 
ref - https://github.com/flutter/flutter-intellij/issues/7000#issuecomment-1952854934

**Comment by KemalEnigma** [comment]
> Can you please: Select Help > Find Action from the Android Studio menu. Look for Registry... Find the ide.browser.jcef.sandbox.enable option in the list and disable it Restart
> 
> ref - [flutter/flutter-intellij#7000 (comment)](https://github.com/flutter/flutter-intellij/issues/7000#issuecomment-1952854934)

Thanks a lot ! This helps
