### ISSUE TITLE
Multilingual Support Error

### ISSUE THREAD

**Issue by zime78** [codota/tabnine-intellij#712]
<img width="744" alt="스크린샷 2024-03-29 오후 10 47 26" src="https://github.com/codota/tabnine-intellij/assets/126031877/368f1efe-87e9-47d7-b0e1-30149860ee53">

다국어 지원이 오류

1. 한국어로 입력이 불가능함.
2. 첨부된 이미지와같이 글자체가 깨져서 보여짐.

gz#30632<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/30632'>Zendesk ticket #30632</a>)</i>

**Comment by TzufTabnine** [comment]
Hi,
English is the only official, naturally supported language.
