### ISSUE TITLE
Issue when trying to copy text or partial code

### ISSUE THREAD

**Issue by nexgendevs** [codota/tabnine-intellij#714]
Can't copy or right click on the code suggestions inside phpstorm. Can't even right click or copy `CTRL+C` on any text inside the answer.

gz#31088<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/31088'>Zendesk ticket #31088</a>)</i>

**Comment by TzufTabnine** [comment]
Hi, Can you please send a video? More details?
