### ISSUE TITLE
Infinity load

### ISSUE THREAD

**Issue by OlirumNunes** [codota/tabnine-intellij#718]
Hello.

Lately I've come across an infinite load when trying to use the Tabnine Chat by Intellij. I've already tried the standard Uninstall and Install procedures, but for some unknown reason this problem still persists. 

ps.: In VSCode, it works normally;

![WhatsApp Image 2024-05-21 at 11 58 08_869565fc](https://github.com/codota/tabnine-intellij/assets/150186772/3d541285-b4f6-4cf9-be5f-066a07624e3c)

**Comment by JoaquinGallardo** [comment]
I´m experiencing the same problem and it seems that there's not a solution about it, at least from what I've researched.

**Comment by mtirtapradja** [comment]
Just try Tabnine an hour ago and also experiencing the same issue. But it works normally on VsCode

**Comment by TzufTabnine** [comment]
Hi,
Please follow this article - https://support.tabnine.com/hc/en-us/articles/5760725346193-Connectivity-possible-issues
If it still not working, please send us the logs - https://support.tabnine.com/hc/en-us/articles/5283541356689-Getting-Tabnine-logs-on-JetBrains
