### ISSUE TITLE
Option to pause plugin until manually resumed

### ISSUE THREAD

**Issue by Komposten** [codota/tabnine-intellij#720]
I use both TabNine and GitHub Copilot as they are both good in different situations, but I don't want to use them both at the same time. What I want to do is have both installed, but then disable the completions for one of them while I am using the other. Copilot supports this case, but TabNine only allows me to snooze it for 1 hour at a time.

It would be really nice if there was an option that would pause the completions until manually turned back on again.

gz#32335<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/32335'>Zendesk ticket #32335</a>)</i>

**Comment by TzufTabnine** [comment]
Hi,
Thanks for the feedback. I will pass it on to our product team.

**Comment by Komposten** [comment]
I don't see any changes in the plugin, but I assume it has been added since the issue has been closed. Where can I find this option?

**Comment by Komposten** [comment]
Bump

**Comment by TzufTabnine** [comment]
https://docs.tabnine.com/main/getting-started/getting-the-most-from-tabnines-code-completion/pause-snooze

**Comment by Komposten** [comment]
> ### Change the Snooze interval
> ℹ Currently only available in VS Code

This is the issue tracker for IntelliJ, not VS Code. So it seems like the issue needs to be re-opened as it hasn't been implemented yet?
