### ISSUE TITLE
Conflict when nginx and composer cpriego/valet-linux library installed

### ISSUE THREAD

**Issue by rootfebri** [codota/tabnine-intellij#721]
I installed valet using composer and use valet auto install to configure the nginx, once configured the tabnine suddenly not working anymore
![TabNine Debugger](https://github.com/codota/tabnine-intellij/assets/28066525/cbcdd4fb-51e8-4114-9219-e7237287a11c)

gz#32718<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/32718'>Zendesk ticket #32718</a>)</i>

**Comment by rootfebri** [comment]
OS: Ubuntu 24.04 LTS x86_64
Kernel: 6.8.0-35-generic
Packages: 2403 (dpkg), 22 (brew), 27 (flatp
Shell: zsh 5.9

**Comment by TzufTabnine** [comment]
Try this first - https://support.tabnine.com/hc/en-us/articles/5760725346193-Connectivity-possible-issues
And if it is still not working, send us the logs -

**Comment by rootfebri** [comment]
It fixed, but I don't really understand what is going on.
I just follow the instruction
![image](https://github.com/codota/tabnine-intellij/assets/28066525/5719d3b3-2cac-41e5-b992-1e41f136b3ea)

> ./TabNine --diagnose
Running Tabnine diagnostic tool
Connection to Tabnine update server... OK
Connection to Tabnine notification server... OK
Connection to Tabnine API... OK
Connection to Tabnine hub... OK
Connection to Tabnine inference root... Tabnine SaaS - skipping... OK
Connection to Tabnine inference service... OK
Midline Inference... OK
Snippet Inference... OK
Memory Size... OK
CPU Cores... OK

**Comment by rootfebri** [comment]
it happening again
now it have diagnose result
Running Tab
```
nine diagnostic tool
http_proxy: "Not set"
https_proxy: "Not set"
no_proxy: "Not set"
Connection to Tabnine update server... Failed: error sending request for url (https://update.tabnine.com/bundles/version)
Connection to Tabnine notification server... Failed: error sending request for url (https://notify.tabnine.com/health)
Connection to Tabnine API... Failed: error sending request for url (https://api.tabnine.com/health)
Connection to Tabnine hub... Failed: error sending request for url (https://hub.tabnine.com/v9/)
Connection to Tabnine inference root... Tabnine SaaS - skipping... OK
Connection to Tabnine inference service... Failed: error sending request for url (https://c2.p.tabnine.com/health)
Midline Inference... Failed: error sending request for url (https://c2.p.tabnine.com/infer)
Snippet Inference... Failed: error sending request for url (https://c2.p.tabnine.com/infer)
Memory Size... OK
CPU Cores... OK
```

**Comment by TzufTabnine** [comment]
@rootfebri What is the issue now? Can you send us the output of curl -w "\nRoundtrip time is: %{time_total}" [https://api.tabnine.com/health](https://c2.p.tabnine.com/health)

**Comment by rootfebri** [comment]
It's just my computer lost /etc/resolv.conf file after installing valet and nginx.
