### ISSUE TITLE
TabNine Chat: the line height is incorrect, lines are overlapping

### ISSUE THREAD

**Issue by StragaSevera** [codota/tabnine-intellij#722]
Whenever I try to use the TabNine chat, I have the difficulty reading the responses, because the line height is too small, and the lines are overlapping: 
![tabnine_01](https://github.com/codota/tabnine-intellij/assets/6378091/eb0636f9-3850-43ef-80ef-f6030444ac31)
According to the developer tools, there is a class that overrides the default `line-height: 1.3` with a forced `23px` value, which is too small for me:
![tabnine_02](https://github.com/codota/tabnine-intellij/assets/6378091/f506ccef-a9f8-45e9-b737-2089e41f8415)
When I turn this override off, it works perfectly without overlap. Is there a way to, for example, somehow inject my custom CSS to force the line height to be readable?

gz#32905<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/32905'>Zendesk ticket #32905</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @StragaSevera . Do you still have this issue? If so, please let us know if it can be reproduced (share the file and the prompt).
