### ISSUE TITLE
Autocomplete is not working on jetbrains IDE during WSL remote development

### ISSUE THREAD

**Issue by tariqiitju** [codota/tabnine-intellij#724]
Autocomplete work on local development. But while using WSL remote mode, I can see the suggessions, but i cant accept the suggession using tab or any other button. Things works as expected with vs code. The issue only persist in Jetbrains IDE (I've tried pycharm professional , intelij community and ultimate)

gz#34246<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/34246'>Zendesk ticket #34246</a>)</i>

**Comment by TzufTabnine** [comment]
Can you elaborate on your setup? What error are you getting? Can you send us the logs?

**Comment by tariqiitju** [comment]
I have windows 11 machine, my project's are in wsl (fedora).  When I open
wsl project with intelij or pycharm, I can use tabnine chat, I can also see
the code suggestions, but when I press tab it just add whitespace in the
code , while it supposed to accept the suggestion. I tried modifying the
auto complete key in the settings with no luck.

I am not sure if ide log would help or not. I also don't know how can I
find ide log.

**Comment by TzufTabnine** [comment]
https://support.tabnine.com/hc/en-us/articles/5283541356689-Getting-Tabnine-logs-on-JetBrains
