### ISSUE TITLE
hub stays as loading

### ISSUE THREAD

**Issue by pseidl-ds** [codota/tabnine-intellij#726]
![grafik](https://github.com/user-attachments/assets/dbc1cd96-3483-481b-9cb4-31adedd1c5fc)

IntelliJ IDEA 2024.2.0.1 (Ultimate Edition)
Build #IU-242.20224.387, built on August 13, 2024
Licensed to doubleSlash Net-Business GmbH / Patrick Seidl
Subscription is active until May 8, 2025.
Runtime version: 21.0.3+13-b509.4 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
  ide.experimental.ui=true
  scala.erase.compiler.process.jdk.once=false
  org.toml.json.schema=false
Non-Bundled Plugins:
  Batch Scripts Support (1.0.13)
  org.intellij.plugins.hcl (242.20224.159)
  PythonCore (242.20224.300)
  com.jetbrains.rust (242.20224.309)
  google-java-format (1.22.0.0)
  com.jetbrains.jax.ws (242.20224.159)
  com.tabnine.TabNine (1.129.0)
  Pythonid (242.20224.387)
  com.intellij.aqua (242.20224.393)
  com.intellij.ml.llm (242.20224.393)
  PlantUML integration (7.10.1-IJ2023.2)
  com.jetbrains.packagesearch.intellij-plugin (242.0.12)
  com.intellij.jsf (242.20224.159)
  org.sonarlint.idea (10.8.1.79205)
  org.intellij.scala (2024.2.20)
  net.ashald.envfile (3.4.2)
Kotlin: 242.20224.387-IJ

IntelliJ Logfiles attached.
[idea.log](https://github.com/user-attachments/files/16928420/idea.log)

gz#34821<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/34821'>Zendesk ticket #34821</a>)</i>

**Comment by TzufTabnine** [comment]
Hi 
Please try this - https://support.tabnine.com/hc/en-us/articles/5760725346193-Connectivity-possible-issues
If it is not helpful, please send us the IDE proxy settings (if you have any) and the all the logs:
https://support.tabnine.com/hc/en-us/articles/5283541356689-Getting-logs-on-JetBrains

**Comment by pseidl-ds** [comment]
@TzufTabnine:
The connectivity checks were successful and no IDE proxy settings are used. The IntelliJ logs are already attached and no Tabnine logs are available after configuring the log file path like described.

**Comment by TzufTabnine** [comment]
@pseidl-ds What browser do you use? Do you managed to sign in? Do code completions work?

**Comment by pseidl-ds** [comment]
@TzufTabnine I use the IntelliJ Tabnine plugin, so there is no browser involved. No, I could not manage to sign in as the "Loading..." massage is the first thing which appeared after the plugin installation in IntelliJ. As I only see the "Loading..." message, code completions do not work.

**Comment by amirbilu** [comment]
Hi @pseidl-ds - can you share the output of `Get-ChildItem -Recurse | Format-Table FullName` inside `C:\Users\pseidl\.tabnine\
`

**Comment by pseidl-ds** [comment]
@amirbilu Yes, here is the output:
```
PS C:\Users\pseidl\.tabnine> Get-ChildItem -Recurse | Format-Table FullName
FullName
--------
C:\Users\pseidl\.tabnine\4.187.0
C:\Users\pseidl\.tabnine\4.187.0\x86_64-pc-windows-msvc
C:\Users\pseidl\.tabnine\4.187.0\x86_64-pc-windows-msvc\TabNine-deep-cloud.exe
C:\Users\pseidl\.tabnine\4.187.0\x86_64-pc-windows-msvc\TabNine-deep-local.exe
C:\Users\pseidl\.tabnine\4.187.0\x86_64-pc-windows-msvc\TabNine-server-runner.exe
C:\Users\pseidl\.tabnine\4.187.0\x86_64-pc-windows-msvc\TabNine.exe
C:\Users\pseidl\.tabnine\4.187.0\x86_64-pc-windows-msvc\TabNine.zip
C:\Users\pseidl\.tabnine\4.187.0\x86_64-pc-windows-msvc\WD-TabNine.exe
```

**Comment by amirbilu** [comment]
Can you try to remove `.tabnine` dir completely + restart the plugin + resend idea.log?

**Comment by pseidl-ds** [comment]
@amirbilu: After removing the .tabnine dir completely, it worked again. Do you still require the logs? Otherwise, this issue can be closed.

**Comment by TzufTabnine** [comment]
Great!
