### ISSUE TITLE
Use black and white icons in status bar and in tool window

### ISSUE THREAD

**Issue by rakleed** [codota/tabnine-intellij#727]
Please use black and white icons in the status bar and in the tool window as other plugins do.

![CleanShot 2024-09-15 at 00 47 50](https://github.com/user-attachments/assets/6b3a853a-7c63-47ff-8a50-7f890bae5267)

gz#34966<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/34966'>Zendesk ticket #34966</a>)</i>

**Comment by TzufTabnine** [comment]
Thanks for the offer. We will consider that.
