### ISSUE TITLE
Latest update busts file-watching limits

### ISSUE THREAD

**Issue by derekwsgray** [codota/tabnine-intellij#728]
I've had tabnine installed in IntelliJ for a very long time.
I today updated to the latest version, and suddenly I couldn't run `vite` anymore with an error about too many file watchers.
It ran fine outside of the IDE.
I disabled tabnine and it _also_ started working again in the IDE's terminal.

This is on Linux (Mint, based on Ubuntu) btw.

gz#35010<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/35010'>Zendesk ticket #35010</a>)</i>

**Comment by TzufTabnine** [comment]
@derekwsgray Please send us logs

**Comment by derekwsgray** [comment]
Ok. I had to anonymize it first. Here is a series of 4 restarts from yesterday. I had also newly installed Atom Icons, so first tried disabling that to no avail. Then when I disabled TabNine, things were back to normal.

[idea-tabnine.log](https://github.com/user-attachments/files/17028874/idea-tabnine.log)

**Comment by TzufTabnine** [comment]
@derekwsgray Can you please send us the engine logs as well? We will need the full logs so please send that so support@tabine.com

**Comment by derekwsgray** [comment]
Sure, if you tell me where to find them.

**Comment by TzufTabnine** [comment]
https://support.tabnine.com/hc/en-us/articles/5283541356689-Getting-logs-on-JetBrains

**Comment by derekwsgray** [comment]
Well, since you guys update your plugin so often, I already applied the update and can no longer reproduce the issue, so I don't have an engine log from the previous version.

**Comment by derekwsgray** [comment]
The version I had a problem with was 1.134, by the way. Now I have 1.135.0
