### ISSUE TITLE
Jetbrains plugin not initalizing

### ISSUE THREAD

**Issue by Dhanzs-chrome** [codota/tabnine-intellij#729]
Hi there,

from version 1.138.0 the tabnine plugin not loading correctly and unusabe. I tried uninstalling it and removing all tabnine configs and installing it again.
![image](https://github.com/user-attachments/assets/2f2dd81a-6e01-453e-8f03-6f4a7e27f24d)

[tabnine_rCURRENT.txt](https://github.com/user-attachments/files/17110059/tabnine_rCURRENT.txt)

gz#35206<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/35206'>Zendesk ticket #35206</a>)</i>

**Comment by TzufTabnine** [comment]
Can you please close the IDE, delete the [binary ](https://support.tabnine.com/hc/en-us/articles/5232801609105-JetBrains-binary-locations)folder and the [vdb ](https://support.tabnine.com/hc/en-us/articles/24781988831767-VDB-logs)folder and try again?

**Comment by TzufTabnine** [comment]
Also check that - https://support.tabnine.com/hc/en-us/articles/5760725346193-Connectivity-possible-issues

**Comment by Dhanzs-chrome** [comment]
Hi, I reinstalled whole system Pop os 22.04 to Zorin OS and problem is solved. Thanks
