### ISSUE TITLE
Editing in chat not working

### ISSUE THREAD

**Issue by Fredoq** [codota/tabnine-intellij#730]
Jetbrains Rider 2024.2
Tabnine 1.139
MacOs 15.0
Apple M3 Max

When I using Tabnine Chat backspace (delete) and enter (new line) not working. I can't remove anything. It is started I think one-two weeks ago. This behaviour only in Tabnine Chat. Is this a known problem?

gz#35240<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/35240'>Zendesk ticket #35240</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @Fredoq Can you please a short video of the issue and share logs with us (https://support.tabnine.com/hc/en-us/articles/5283541356689-Getting-logs-on-JetBrains)

**Comment by Fredoq** [comment]
Logs and video in attached file

https://github.com/user-attachments/assets/4542312b-0de5-4790-be10-58babb45a392

[console.log](https://github.com/user-attachments/files/17128796/console.log)
[rider-logs-20240925-12375313161504454307207867.zip](https://github.com/user-attachments/files/17128797/rider-logs-20240925-12375313161504454307207867.zip)
[riderlogs_rCURRENT.log](https://github.com/user-attachments/files/17128798/riderlogs_rCURRENT.log)

**Comment by TzufTabnine** [comment]
Hi @Fredoq, We couldn't replicate and didn't see anything in the logs. Can you send us the list of the plugins? Did it reproduce in any other IDE (if you have any)

**Comment by Fredoq** [comment]
Plugins:

<img width="347" alt="image" src="https://github.com/user-attachments/assets/79ec61cb-f5a0-41b7-9058-a9e75ee00451">

I will try to turn of them and then try again

**Comment by Fredoq** [comment]
After I turn off other plugins I still can't editing text. I install another plugin (Codeium) and there in chat  I can't remove text too so I think this is something with IDE. I will reinstall and recheck after.

**Comment by Fredoq** [comment]
FYI After downgrading rider to 2024.1.6,  chat start working fine there.

**Comment by TzufTabnine** [comment]
Great!

**Comment by mosesyap** [comment]
I am having this issue on Jetbrains product since 2024.2.x and 2024.3.  The solution cannot e please downgrade to 2024.1.6
