### ISSUE TITLE
AppData/Roaming/TabNine Directory is taking up all the space on my C drive

### ISSUE THREAD

**Issue by fangzhegeo** [codota/tabnine-intellij#731]
Seems TabNine is consuming an excessive amount of disk space. The directory at the following path:
`C:\Users\{my name}\AppData\Roaming\TabNine\servers\vdb\1.7.3-fix.1\download\storage\collections\tabnine_sparse_2\0` contains two directories, `segments` and `temp_segments`, which together occupy around 109 GB of space. These directories are filled with numerous `.sst` files.

![image](https://github.com/user-attachments/assets/bc09855f-a676-4f6d-b5f4-9443b3fb3fc5)

![image](https://github.com/user-attachments/assets/60d1b22c-53f4-49a7-8fc3-a9152799e8af)

gz#35246<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/35246'>Zendesk ticket #35246</a>)</i>

**Comment by TzufTabnine** [comment]
@fangzhegeo Please close the IDE and then delete the folder:
C:\Users\{my name}\AppData\Roaming\TabNine\servers\vdb
. In addition, if there are some files that you don't want to index, please specify them:
https://docs.tabnine.com/main/welcome/readme/personalization/tabnines-personalization-in-depth#what-files-are-being-indexed
