### ISSUE TITLE
Latest Version of the source Code?

### ISSUE THREAD

**Issue by tobiashochguertel** [codota/tabnine-intellij#732]
There are newer versions in the Jetbrains marketplace as in this repository. In the repository the latest commit / activity is from March 2024 or 2023.

Did the strategy change to closed source somehow over the year?

I want to modify the Tabnine IntelliJ Plugin for my needs, and create a pull request afterwards or release a separated plugin.

But I think that only makes sense when I can look at the source code of the current/ latest version of the plugin. 

Is it possible that Tabnine updates this repository with the latest changes of the latest released version of the plugin?

gz#35751<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/35751'>Zendesk ticket #35751</a>)</i>

**Comment by TzufTabnine** [comment]
Hi, @tobiashochguertel, We closed our repo for a reason (IP etc.) and we won't share the source code.
