### ISSUE TITLE
API Documentation of Tabnine Chat?

### ISSUE THREAD

**Issue by tobiashochguertel** [codota/tabnine-intellij#733]
I want to write a plugin to use the Tabnine Chat more efficiently. I'm looking for a API and Endpoint Documentation. 

Is that available?

gz#35752<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/35752'>Zendesk ticket #35752</a>)</i>

**Comment by TzufTabnine** [comment]
Hi, you can develop such a plugin yourself. Here is the guide: https://github.com/codota/TabNine/blob/master/HowToWriteAClient.md

**Comment by tobiashochguertel** [comment]
@TzufTabnine Thanks for this information. I checked out already and the current code of this repository https://github.com/codota/tabnine-intellij to figure out how the chat works and how I can build my own TabNine Chat App. 

**It's with the provided Information very hard to do.**

The Chat is a different App at all. It's a Website which gets downloaded when TabNine binary is started, as I discovered. The source code of the Chat Website is minified, so no longer readable for humans. With the JCEF / Browser Debug Window in the IntelliJ Plugin, I'm able to see the requests which are being made by the chat website when I submit a question. That is a little help.

One of these requests which are made look interesting for my purposes, that is a POST to `http://127.0.0.1:49825/generate` but the Payload is a stream or something like it, not readable for humans. So I don't know how to create this request myself.

- Can you please ask the developers for an API Specification on what kind of data they expect from me to send via POST to the `generate` endpoint?

- or / and can you ask for the non minified source code of the Chat Website App?

_I'm a paying user of TabNine since a year or longer._
