### ISSUE TITLE
Not loadding

### ISSUE THREAD

**Issue by BBorges23** [codota/tabnine-intellij#734]
I am currently using PHPStorm version 2024.2.3 and Tabnine version 1.149.0, but it's not working. It gets stuck on 'loading' and never opens.

I apologize for the lack of detailed information or any vague descriptions, as this is my first time seeking help here.

gz#35814<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/35814'>Zendesk ticket #35814</a>)</i>

**Comment by TzufTabnine** [comment]
Please delete Tabnine completely from your machine.
See [here](https://support.tabnine.com/hc/en-us/articles/17823949049745) how to do that
Are you behind Proxy/VPN/Firewall/Antivirus, or do you have some connectivity issues? Please follow the steps [here](https://support.tabnine.com/hc/en-us/articles/5760725346193-Connectivity-possible-issues).
Please use Chrome as your default browser. 
Try running the curl command in your terminal/CMD (not Powershell) to your server URL and send us the output. 

```
curl -w "\nRoundtrip time is: %{time_total}" https://c2.p.tabnine.com/health

curl -w "\nRoundtrip time is: %{time_total}" https://api.tabnine.com/health
```

Please send us the JetBrains log files (JetBrains idea+engine + Chat console logs). See [here](https://support.tabnine.com/hc/en-us/articles/5283541356689-Getting-Tabnine-logs-on-JetBrains) how to do that.

**Comment by BBorges23** [comment]
That worked! Thank you so much for your time and help.
