### ISSUE TITLE
Cannot partially copy code from the chat window

### ISSUE THREAD

**Issue by jSharpWolf** [codota/tabnine-intellij#737]
Copy/Paste with keyboard shortcuts does not work in the chat tab at all. Not even in generated code.
Sometimes you just want to partially copy code, especially since most AI tools tend to overexplain and be overly detailed and redundant when you just want a small section of the answer. You can mark code, but not copy it.

You can select code here:
![image](https://github.com/user-attachments/assets/449f0680-405b-446d-9566-b077e15feee1)
But if you press Ctrl+C, nothing in the clipboard is changed.

This is especially nasty, since sometimes the "Apply" function doesn't work and you need to copy manually (that's a different bug).
Tested with Rider 2024.3

gz#37298<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/37298'>Zendesk ticket #37298</a>)</i>

**Comment by TzufTabnine** [comment]
@jSharpWolf We are looking into it

**Comment by jSharpWolf** [comment]
@TzufTabnine I found out the reason, after testing in PyCharm and IntelliJ.

The following standard shortcut from dotCover "Cover Selected Tests" is also bound to ctrl+c and interfers with the selection. If I remove said shortcut it works.
![image](https://github.com/user-attachments/assets/0de2f68f-4995-4d19-b15c-00fba21c5745)

But be aware: This is a standard Rider setting, not custom. No idea why a dotCover shortcut would do anything in the Tabnine window.

**Comment by TzufTabnine** [comment]
Thank you for sharing; I'm glad it is working for you now. I'll pass this information on to the team.
